spring:
  application:
    name: nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9001
logging:
  file: consu.log
  level:
    root: info
    cn.moretv.cloud.consumer: debug
